spring:
  profiles:
    active: local

jwt:
  secretKey: djawlifhlwalawdawdhkawhdkawudhakuwdhkuawhfukawfhkuawhfawkesjiawfukawfgaw
  access-token-expire-time: 1800000 # 30분
  refresh-token-expire-time: 2592000000 # 30일

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/pill?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1111
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_KEY}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분